#**Reconhecimento de Padrões**

*Trabalho 4: PCA e Classificador SVM*

*- Kernel Linear*

*- Renoir Sampaio (389113)*

##**Preparação dos dados e informações**


In [ ]:
# Importando bibliotecas
import numpy as np # Algebra Linear
from numpy.linalg import inv, det, norm # Inversa e determinante
import pandas as pd # Processamento de dados
import seaborn as sns # Plotagem
import matplotlib.pyplot as plt # Plotagem
import math # Matemática
from random import randint, uniform # Aleatoriedade
from sklearn.metrics import accuracy_score, recall_score, precision_score
from sklearn.metrics import classification_report, confusion_matrix
!pip install qpsolvers
from qpsolvers import solve_qp

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
# Realiza a leitura do dataset
df = pd.read_csv('/content/TEJ - Normalized_2013_0430_Taiwan_data.csv', sep=',', encoding='latin-1', header=None)

In [ ]:
# Renomeando coluna de classes
df = df.drop([0])
df = df.rename(columns = {0: 'classe'}, inplace = False)

In [ ]:
# Selecionando atributos que serão usados
df = df.iloc[0:1000, 0:94]

In [ ]:
# Tornando dados do tipo float
df = df.astype(float)

In [ ]:
# Infomações sobre a base de dados
print(f'Número de amostras da base de dados: {df.shape[0]}')
print(f'Número de atributos da base de dados: {df.shape[1]-1}')
vetor_classes = np.unique(df['classe'])
print(f'Classes presentes na base de dados: {vetor_classes.tolist()}')

Número de amostras da base de dados: 1000
Número de atributos da base de dados: 93
Classes presentes na base de dados: [0.0, 1.0]


Nota: Esta base de dados foram coletados do Taiwan Economic Journal para os anos de 1999 a 2009. A falência da empresa foi definida com base nos regulamentos de negócios da Bolsa de Valores de Taiwan.

In [ ]:
# p Atributos (linhas) e N amostras (colunas)
df = df.T

In [ ]:
# Mostrando o dataset
df

1         2         3     ...      998       999       1000
classe  1.000000  1.000000  1.000000  ...  0.000000  0.000000  0.000000
1       0.370594  0.464291  0.426071  ...  0.494418  0.476186  0.512309
2       0.424389  0.538214  0.499019  ...  0.553969  0.539686  0.579427
3       0.405750  0.516730  0.472295  ...  0.544087  0.526527  0.566358
4       0.601457  0.610235  0.601450  ...  0.607713  0.607742  0.612296
...          ...       ...       ...  ...       ...       ...       ...
89      0.601453  0.610237  0.601449  ...  0.607709  0.607741  0.612294
90      0.827890  0.839969  0.836774  ...  0.840836  0.840380  0.842820
91      0.290202  0.283846  0.290189  ...  0.276633  0.279919  0.283418
92      0.026601  0.264577  0.026555  ...  0.026799  0.026996  0.026898
93      0.564050  0.570175  0.563706  ...  0.565195  0.565977  0.565621

[94 rows x 1000 columns]

In [ ]:
# Divisão treino e teste
def divTesteTreinoTransp(df, percent, lengh):
  i = lengh*percent/100
  return df[0:int(i)], df[int(i):lengh]

In [ ]:
# Criação de função para cálculo de acurácia baseado na coluna 'classe'  
# da tabela dados gerais, onde estão localizados os labels
def getAccuracy(testSet, predictions, tamanho):
    correct = 0
    for x in range(len(testSet)):
        if (testSet[x] == predictions[x]):
            correct += 1
    return (correct/float(len(testSet))) * 100.0

In [ ]:
# Criar dataset aleatório
df_sample = df.T.sample(frac=1)
df_sample = df_sample.T

In [ ]:
# Divisão treino e teste 70% e 30%
treino, teste = divTesteTreinoTransp(df_sample.T, 70, len(df.T))
treino = treino.T
teste = teste.T

In [ ]:
# Mostrando dados de treino
treino

505       117       497  ...       818       972       114
classe  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1       0.479988  0.485595  0.489251  ...  0.477405  0.518159  0.479355
2       0.540340  0.570377  0.550698  ...  0.542085  0.578990  0.534834
3       0.535789  0.541678  0.531667  ...  0.530864  0.561700  0.532951
4       0.602855  0.603237  0.597220  ...  0.605025  0.600996  0.598574
...          ...       ...       ...  ...       ...       ...       ...
89      0.602853  0.603235  0.597217  ...  0.605026  0.600992  0.598575
90      0.840350  0.841480  0.840619  ...  0.840426  0.842516  0.840175
91      0.277582  0.280860  0.275184  ...  0.276851  0.280693  0.276086
92      0.027084  0.027180  0.026815  ...  0.026881  0.026796  0.026791
93      0.566252  0.566514  0.565271  ...  0.565554  0.565182  0.565159

[94 rows x 700 columns]

In [ ]:
# Mostrando dados de teste
teste

715       622       91   ...       301       4         36 
classe  0.000000  0.000000  0.000000  ...  0.000000  1.000000  0.000000
1       0.526300  0.514405  0.476673  ...  0.478038  0.399844  0.475162
2       0.574193  0.575392  0.512048  ...  0.527148  0.451265  0.564544
3       0.576316  0.569088  0.531452  ...  0.530810  0.457733  0.525028
4       0.617197  0.612167  0.592499  ...  0.599338  0.583541  0.614278
...          ...       ...       ...  ...       ...       ...       ...
89      0.617194  0.612165  0.592499  ...  0.599335  0.583538  0.614277
90      0.841898  0.841646  0.839197  ...  0.839632  0.834697  0.841252
91      0.280952  0.277497  0.277775  ...  0.278000  0.281721  0.279474
92      0.026936  0.026858  0.026633  ...  0.025803  0.026697  0.027115
93      0.565765  0.565459  0.564271  ...  0.492121  0.564663  0.566339

[94 rows x 300 columns]

In [ ]:
# Retirando classe do dataset de treino
treino_noclass = treino.T.drop(columns = ['classe'])
treino_noclass = treino_noclass.T

In [ ]:
# Retirando classe do dataset de teste
teste_noclass = teste.T.drop(columns = ['classe'])
teste_noclass = teste_noclass.T

In [ ]:
# Vetor média dos atributos de treino
treino_noclass_mean = treino_noclass.T.mean()

In [ ]:
# Subtrair o valor médio de cada atributo da base de dados de treino
df_new = []
for i in range(len(treino_noclass)):
  df_prov = []
  for j in range(len(treino_noclass.T)):
    df_prov.append(treino_noclass.values[i][j] - treino_noclass_mean.values[i])
  df_new.append(df_prov)
df_new = pd.DataFrame(df_new)

In [ ]:
# Matriz COV em função dos dados de treino
matrixCov_treino = pd.DataFrame.cov(df_new.T)

In [ ]:
# Autovetores (U) autovalores (sigma)
sigma, U = np.linalg.eig(matrixCov_treino)

In [ ]:
# Transformando 'U' em formato DataFrame
U = pd.DataFrame(U)

In [ ]:
# Multiplicando qualquer coluna por ela mesma, valor esperado: 1
U[0].T @ U[0]

1.0000000000000002

In [ ]:
# Transformando sigma em matriz diagonal
d_sigma = np.diag(sigma)

In [ ]:
# Transformando matriz diagonal 'sigma' em formato DataFrame
d_sigma = pd.DataFrame(d_sigma)

In [ ]:
# Somatório dos autovalores
sum_sigma = sigma.sum()

In [ ]:
# Definindo q para dimenção da matriz de U transformada
# buscando 95% dos valores
for i in range(df_new.shape[0]):
  soma_prov = sigma[0:i].sum()
  porcent_sigma = soma_prov / sum_sigma * 100
  print(f'Com {i}: {int(porcent_sigma)}%')
  if porcent_sigma >= 95:
    q = i
    break
print(f'Sendo assim, a quantidade de colunas escolhidas foi {q}')

Com 0: 0%
Com 1: 50%
Com 2: 68%
Com 3: 78%
Com 4: 85%
Com 5: 88%
Com 6: 91%
Com 7: 93%
Com 8: 94%
Com 9: 95%
Sendo assim, a quantidade de colunas escolhidas foi 9


In [ ]:
# Criar matriz transformada, valores descorrelacionados
matrix_transform = U.T @ df_new

In [ ]:
# Matriz COV por multiplicação matricial com autovetores
# e dados de treino transformados
matrixCov_treino_transform = ((U @ matrixCov_treino) @ U.T)

In [ ]:
# Matriz identidade por serem vetores ortogonais
matrizIdentidade = U.T @ U

In [ ]:
# Decompondo matriz de teste
df_decomp = ((U @ d_sigma) @ U.T)

In [ ]:
# Nova matriz de tranformação (que antes era o próprio U) será de dimenção pxq
# onde p ainda sera o número de atributos e q < p (definido previamente). 
# U de dimenção pxq transposto que multiplica df_new de dimenção pxN.
U_transf = U.iloc[:, 0:q]
matrix_transform_new = U_transf.T @ df_new

In [ ]:
# Construindo o modelo para cada novo vetor dos dados de teste
df_teste = []
for i in range(len(teste_noclass)):
  df_prov = []
  for j in range(len(teste_noclass.T)):
    df_prov.append(teste_noclass.values[i][j] - treino_noclass_mean.values[i])
  df_teste.append(df_prov)
df_teste = pd.DataFrame(df_teste)
matrix_transform_teste = U_transf.T @ df_teste

## ***SVM (Linear):***

In [ ]:
# 15 interações
all_accuracy_treino = []
all_accuracy_teste = []
melhor_acuracia = 0
melhor_C = 0
for p in range(15):
  print('#####################################################################')
  print(f'Interação: {p+1}/15')
  # Ordem do Kernel polinomial
  d = randint(30, 100)
  print(f'Valor de d = {d}')

  # Matriz X do treino
  X = matrix_transform_new

  # Vetor com as classes do treino
  treino_sample_class0 = treino.T.loc[treino.T['classe'] == 0]
  treino_sample_class1 = treino.T.loc[treino.T['classe'] == 1]
  y0 = -np.ones(treino_sample_class0.shape[0])
  y0 = pd.DataFrame(y0)
  y1 = np.ones(treino_sample_class1.shape[0])
  y1 = pd.DataFrame(y1)
  y = pd.concat([y0,y1])
  y_reset_index = y.reset_index(drop=True)

  # Cálculo do Kernel polinomial
  K = ((X.T @ X + 1) ** d) # Kernel linear

  # Formulação da programação quadrática
  C = uniform(0.001, 1000) # Constante de relaxamento
  a = np.zeros((X.shape[1], X.shape[1]), int)
  np.fill_diagonal(a, y_reset_index)
  y_diag = pd.DataFrame(a)
  P = ((y_diag * K) * y_diag)
  P = (P + P.T)/2
  P = np.array(P)
  P += np.identity(X.shape[1]) * 0.001
  P = P.astype('double')
  q = -C*np.ones(X.shape[1])
  G = -np.identity(X.shape[1])
  G = G.astype('double')
  h = np.zeros(X.shape[1])
  A = np.array(y_reset_index.T)[0]
  beq = np.array([0])

  # Chamada da função de otimização
  alpha = solve_qp(P, q, G, h, A, beq)

  # Achar vetores suporte
  vet_sup = np.argwhere(alpha > 1e-3)

  # Cálculo da constante b
  b = 0
  for i in vet_sup[:,0]:
    b = b + (1 / y_reset_index.iloc[i].values[0])
    for j in vet_sup[:,0]:
      b = b - (y_reset_index.iloc[j].values[0] * alpha[j] * K.iloc[j,i])
  b = b/vet_sup.shape[0]

  ############################ FASE DE TESTE ##################################
  
  # Matriz X do teste
  X = matrix_transform_teste

  # Vetor com as classes do teste
  teste_sample_class0 = teste.T.loc[teste.T['classe'] == 0]
  teste_sample_class1 = teste.T.loc[teste.T['classe'] == 1]
  y0 = -np.ones(teste_sample_class0.shape[0])
  y0 = pd.DataFrame(y0)
  y1 = np.ones(teste_sample_class1.shape[0])
  y1 = pd.DataFrame(y1)
  y = pd.concat([y0,y1])
  y_reset_index_teste = y.reset_index(drop=True)

  # Cálculo do Kernel polinomial
  K = ((X.T @ X + 1) ** d) # Kernel linear

  # Estimar classes
  aux = 0
  for j in vet_sup[:,0]:
    if j < K.shape[0]:
      aux = aux + (y_reset_index_teste.iloc[j].values[0] * alpha[j] * K.iloc[j,:])
  y_est_teste = np.sign((aux + b).T)
  y_est_teste = y_est_teste.astype('double')
  y_est_teste = pd.DataFrame(y_est_teste)

  # Vetores de índices reais para comparação
  indices_teste = y_reset_index_teste.T.values[0]
  indices_teste = indices_teste.astype(float)

  # Vetores de índices previstos para comparação
  indices_previstos_teste = y_est_teste.T.values[0]
  indices_previstos_teste = indices_previstos_teste.astype(float)
  print(f'Matriz de confusão:\n{confusion_matrix(indices_teste, indices_previstos_teste)}')

  # Teste de acurácia com labels corretos e labels previstos (classificados)
  accuracy_teste = getAccuracy(indices_teste, indices_previstos_teste, len(indices_teste))
  all_accuracy_teste.append(accuracy_teste)
  print(f'Acurácia de teste dessa interação: {int(accuracy_teste)}%')
  print('#####################################################################')
  if p < 14:
    print('|/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/_')

  # Melhor acurácia e hiperparâmetros
  if accuracy_teste > melhor_acuracia:
    melhor_acuracia = accuracy_teste
    melhor_C = C

print('\n')
# Média total das acurácias de teste
print(f'Média das acurácias de teste: {int(np.mean(all_accuracy_teste))}%')
# Melhor hiperparâmetro
print(f'No melhor valor de acurácia do teste, que foi igual a {int(melhor_acuracia)}%, o melhor valor para hiperparâmetro C foi {melhor_C}')

#####################################################################
Interação: 1/15
Valor de d = 78
Matriz de confusão:
[[273  10]
 [ 15   2]]
Acurácia de teste dessa interação: 91%
#####################################################################
|/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/_
#####################################################################
Interação: 2/15
Valor de d = 82
Matriz de confusão:
[[273  10]
 [ 15   2]]
Acurácia de teste dessa interação: 91%
#####################################################################
|/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/_
#####################################################################
Interação: 3/15
Valor de d = 60
Matriz de confusão:
[[276   7]
 [ 15   2]]
Acurácia de teste dessa interação: 92%
#####################################################################
|/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/_
############################

Nota: Podemos notar que, para esse problema, o kernel do tipo linear nos retorna uma boa acurácia, porém não consegue ter um bom resultado de classificação, como vemos no baixo valor de recall e a baixa precisão. 