#**Reconhecimento de Padrões**

*Trabalho 4: PCA e Classificador SVM*

*- Kernel RBF*

*- Renoir Sampaio (389113)*

##**Preparação dos dados e informações**


In [1]:
# Importando bibliotecas
import numpy as np # Algebra Linear
from numpy.linalg import inv, det, norm # Inversa e determinante
import pandas as pd # Processamento de dados
import seaborn as sns # Plotagem
import matplotlib.pyplot as plt # Plotagem
import math # Matemática
from random import randint, uniform # Aleatoriedade
from sklearn.metrics import accuracy_score, recall_score, precision_score
from sklearn.metrics import classification_report, confusion_matrix
!pip install qpsolvers
from qpsolvers import solve_qp

  Created wheel for qpsolvers: filename=qpsolvers-1.4-cp36-none-any.whl size=18455 sha256=39709f05b0783b5062e4368ba2a79d573c68e1960595158dd2bfbc237a35c260
  Stored in directory: /root/.cache/pip/wheels/ce/a7/5f/2af411a5eea3909096a303f84b7d6ff84e440081e8baccb4f2
  Created wheel for quadprog: filename=quadprog-0.1.7-cp36-cp36m-linux_x86_64.whl size=299426 sha256=b8337b2402b042860bd715361128bc5d5c8408af8005817a7486c413bf08e87f
  Stored in directory: /root/.cache/pip/wheels/36/dd/b1/849989444c0a5930927b260663019b7da6cff864fc224c2747
Successfully built qpsolvers quadprog


In [2]:
# Realiza a leitura do dataset
df = pd.read_csv('/content/TEJ - Normalized_2013_0430_Taiwan_data.csv', sep=',', encoding='latin-1', header=None)

In [3]:
# df = df.select_dtypes(include=['number'])
df = df.drop([0])
df = df.rename(columns = {0: 'classe'}, inplace = False)

In [4]:
# Selecionando atributos que serão usados
df = df.iloc[0:500, 0:94]

In [5]:
df = df.astype(float)
# df.info()

In [6]:
# Infomações sobre a base de dados
print(f'Número de amostras da base de dados: {df.shape[0]}')
print(f'Número de atributos da base de dados: {df.shape[1]-1}')
vetor_classes = np.unique(df['classe'])
print(f'Classes presentes na base de dados: {vetor_classes.tolist()}')

Número de amostras da base de dados: 500
Número de atributos da base de dados: 93
Classes presentes na base de dados: [0.0, 1.0]


Nota: Esta base de dados foram coletados do Taiwan Economic Journal para os anos de 1999 a 2009. A falência da empresa foi definida com base nos regulamentos de negócios da Bolsa de Valores de Taiwan.

In [7]:
# p Atributos (linhas) e N amostras (colunas)
df = df.T

In [8]:
# Mostrando o dataset
df

1         2         3    ...       498       499       500
classe  1.000000  1.000000  1.000000  ...  0.000000  0.000000  0.000000
1       0.370594  0.464291  0.426071  ...  0.496807  0.478721  0.493394
2       0.424389  0.538214  0.499019  ...  0.561819  0.535597  0.542303
3       0.405750  0.516730  0.472295  ...  0.549280  0.531399  0.540232
4       0.601457  0.610235  0.601450  ...  0.604333  0.598481  0.595980
...          ...       ...       ...  ...       ...       ...       ...
89      0.601453  0.610237  0.601449  ...  0.604329  0.598480  0.595978
90      0.827890  0.839969  0.836774  ...  0.841495  0.840171  0.840470
91      0.290202  0.283846  0.290189  ...  0.281880  0.277645  0.280401
92      0.026601  0.264577  0.026555  ...  0.027048  0.027300  0.027180
93      0.564050  0.570175  0.563706  ...  0.566144  0.566796  0.566513

[94 rows x 500 columns]

In [9]:
# Divisão treino e teste
def divTesteTreinoTransp(df, percent, lengh):
  i = lengh*percent/100
  return df[0:int(i)], df[int(i):lengh]

In [10]:
# Criação de função para cálculo de acurácia baseado na coluna 'classe'  
# da tabela dados gerais, onde estão localizados os labels
def getAccuracy(testSet, predictions, tamanho):
    correct = 0
    for x in range(len(testSet)):
        if (testSet[x] == predictions[x]):
            correct += 1
    return (correct/float(len(testSet))) * 100.0

In [11]:
# Criar dataset aleatório
df_sample = df.T.sample(frac=1)
df_sample = df_sample.T

In [12]:
# Divisão treino e teste 70% e 30%
treino, teste = divTesteTreinoTransp(df_sample.T, 70, len(df.T))
treino = treino.T
teste = teste.T

In [13]:
# Mostrando dados de treino
treino

325       33        482  ...       341       126       260
classe  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1       0.520645  0.505874  0.480915  ...  0.465168  0.504753  0.471360
2       0.563781  0.570704  0.539686  ...  0.541430  0.581880  0.538923
3       0.573211  0.559827  0.534986  ...  0.515820  0.576102  0.536164
4       0.601630  0.601169  0.597421  ...  0.600455  0.605133  0.595029
...          ...       ...       ...  ...       ...       ...       ...
89      0.601631  0.601169  0.597423  ...  0.600454  0.605128  0.595031
90      0.841480  0.841432  0.840251  ...  0.840526  0.842176  0.840088
91      0.281703  0.279111  0.286540  ...  0.282192  0.280654  0.279163
92      0.027083  0.027119  0.029941  ...  0.027144  0.027123  0.025862
93      0.566248  0.566351  0.568931  ...  0.566420  0.566362  0.528481

[94 rows x 350 columns]

In [14]:
# Mostrando dados de teste
teste

98        465       141  ...       208       370       8  
classe  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1       0.496807  0.419100  0.500122  ...  0.492322  0.512748  0.508361
2       0.570704  0.467292  0.554405  ...  0.547700  0.561655  0.570922
3       0.543552  0.466513  0.542106  ...  0.543230  0.558863  0.559077
4       0.602848  0.591944  0.600455  ...  0.604340  0.605198  0.601738
...          ...       ...       ...  ...       ...       ...       ...
89      0.602848  0.591939  0.600456  ...  0.604341  0.605192  0.601739
90      0.841634  0.836229  0.840890  ...  0.840588  0.841403  0.841459
91      0.277752  0.282207  0.277775  ...  0.278563  0.279767  0.278607
92      0.026824  0.026641  0.026885  ...  0.027014  0.026856  0.027031
93      0.565312  0.564321  0.565569  ...  0.566038  0.565451  0.566089

[94 rows x 150 columns]

In [15]:
# Retirando classe do dataset de treino
treino_noclass = treino.T.drop(columns = ['classe'])
treino_noclass = treino_noclass.T

In [16]:
# Retirando classe do dataset de teste
teste_noclass = teste.T.drop(columns = ['classe'])
teste_noclass = teste_noclass.T

In [17]:
# Vetor média dos atributos de treino
treino_noclass_mean = treino_noclass.T.mean()

In [18]:
# Subtrair o valor médio de cada atributo da base de dados de treino
df_new = []
for i in range(len(treino_noclass)):
  df_prov = []
  for j in range(len(treino_noclass.T)):
    df_prov.append(treino_noclass.values[i][j] - treino_noclass_mean.values[i])
  df_new.append(df_prov)
df_new = pd.DataFrame(df_new)

In [19]:
# Matriz COV em função dos dados de treino
matrixCov_treino = pd.DataFrame.cov(df_new.T)

In [20]:
# Autovetores (U) autovalores (sigma)
sigma, U = np.linalg.eig(matrixCov_treino)

In [21]:
# Transformando 'U' em formato DataFrame
U = pd.DataFrame(U)

In [22]:
# Multiplicando qualquer coluna por ela mesma, valor esperado: 1
U[0].T @ U[0]

1.0000000000000002

In [23]:
# Transformando sigma em matriz diagonal
d_sigma = np.diag(sigma)

In [24]:
# Transformando matriz diagonal 'sigma' em formato DataFrame
d_sigma = pd.DataFrame(d_sigma)

In [25]:
# Somatório dos autovalores
sum_sigma = sigma.sum()

In [26]:
# Definindo q para dimenção da matriz de U transformada
# buscando 95% dos valores
for i in range(df_new.shape[0]):
  soma_prov = sigma[0:i].sum()
  porcent_sigma = soma_prov / sum_sigma * 100
  print(f'Com {i}: {int(porcent_sigma)}%')
  if porcent_sigma >= 95:
    q = i
    break
print(f'Sendo assim, a quantidade de colunas escolhidas foi {q}')

Com 0: 0%
Com 1: 46%
Com 2: 64%
Com 3: 74%
Com 4: 83%
Com 5: 88%
Com 6: 90%
Com 7: 92%
Com 8: 94%
Com 9: 95%
Sendo assim, a quantidade de colunas escolhidas foi 9


In [27]:
# Criar matriz transformada, valores descorrelacionados
matrix_transform = U.T @ df_new

In [28]:
# Matriz COV por multiplicação matricial com autovetores
# e dados de treino transformados
matrixCov_treino_transform = ((U @ matrixCov_treino) @ U.T)

In [29]:
# Matriz identidade por serem vetores ortogonais
matrizIdentidade = U.T @ U

In [30]:
# Decompondo matriz de teste
df_decomp = ((U @ d_sigma) @ U.T)

In [31]:
# Nova matriz de tranformação (que antes era o próprio U) será de dimenção pxq
# onde p ainda sera o número de atributos e q < p (definido previamente). 
# U de dimenção pxq transposto que multiplica df_new de dimenção pxN.
U_transf = U.iloc[:, 0:q]
matrix_transform_new = U_transf.T @ df_new

In [32]:
# Construindo o modelo para cada novo vetor dos dados de teste
df_teste = []
for i in range(len(teste_noclass)):
  df_prov = []
  for j in range(len(teste_noclass.T)):
    df_prov.append(teste_noclass.values[i][j] - treino_noclass_mean.values[i])
  df_teste.append(df_prov)
df_teste = pd.DataFrame(df_teste)
matrix_transform_teste = U_transf.T @ df_teste

## ***SVM (RBF):***

In [33]:
# 15 interações
all_accuracy_treino = []
all_accuracy_teste = []
melhor_acuracia = 0
melhor_C = 0
melhor_gama = 0
for p in range(15):
  print('#####################################################################')
  print(f'Interação: {p+1}/15')
  # Ordem do Kernel polinomial
  d = randint(15, 50)
  print(f'Valor de d = {d}')

  # Matriz X do treino
  X = matrix_transform_new

  # Vetor com as classes do treino
  treino_sample_class0 = treino.T.loc[treino.T['classe'] == 0]
  treino_sample_class1 = treino.T.loc[treino.T['classe'] == 1]
  y0 = -np.ones(treino_sample_class0.shape[0])
  y0 = pd.DataFrame(y0)
  y1 = np.ones(treino_sample_class1.shape[0])
  y1 = pd.DataFrame(y1)
  y = pd.concat([y0,y1])
  y_reset_index = y.reset_index(drop=True)

  # Cálculo do Kernel polinomial
  # Kernel RBF
  # Valor de Gama
  gama = uniform(0.001, 1000)
  K = pd.DataFrame(index=[i for i in range(X.shape[1])], columns=[i for i in range(X.shape[1])]) 
  for i in range(X.shape[1]):
      for j in range(X.shape[1]):
          K.iloc[i, j] = np.exp(-gama * (np.linalg.norm(X.iloc[:, i].T - X.iloc[:, j]) ** 2))

  # Formulação da programação quadrática
  C = uniform(0.001, 1000) # Constante de relaxamento
  a = np.zeros((X.shape[1], X.shape[1]), int)
  np.fill_diagonal(a, y_reset_index)
  y_diag = pd.DataFrame(a)
  P = ((y_diag @ K) @ y_diag)
  P = (P + P.T)/2
  P = np.array(P)
  P += np.identity(X.shape[1]) * 0.001
  P = P.astype('double')
  q = -C*np.ones(X.shape[1])
  G = -np.identity(X.shape[1])
  P = P.astype('double')
  h = np.zeros(X.shape[1])
  A = np.array(y_reset_index.T)[0]
  beq = np.array([0])

  # Chamada da função de otimização
  alpha = solve_qp(P, q, G, h, A, beq)

  # Achar vetores suporte
  vet_sup = np.argwhere(alpha > 1e-3)

  # Cálculo da constante b
  b = 0
  for i in vet_sup[:,0]:
    b = b + (1 / y_reset_index.iloc[i].values[0])
    for j in vet_sup[:,0]:
      b = b - (y_reset_index.iloc[j].values[0] * alpha[j] * K.iloc[j,i])
  b = b/vet_sup.shape[0]

  ############################ FASE DE TESTE ##################################
  
  # Matriz X do teste
  X = matrix_transform_teste

  # Vetor com as classes do teste
  teste_sample_class0 = teste.T.loc[teste.T['classe'] == 0]
  teste_sample_class1 = teste.T.loc[teste.T['classe'] == 1]
  y0 = -np.ones(teste_sample_class0.shape[0])
  y0 = pd.DataFrame(y0)
  y1 = np.ones(teste_sample_class1.shape[0])
  y1 = pd.DataFrame(y1)
  y = pd.concat([y0,y1])
  y_reset_index_teste = y.reset_index(drop=True)

  # Cálculo do Kernel polinomial
  # Kernel RBF
  # Valor de Gama
  gama = uniform(0.001, 1000)
  K = pd.DataFrame(index = [i for i in range(X.shape[1])], columns = [i for i in range(X.shape[1])]) 
  for i in range(X.shape[1]):
      for j in range(X.shape[1]):
          K.iloc[i, j] = np.exp(-gama * (np.linalg.norm(X.iloc[:, i].T - X.iloc[:, j]) ** 2))

  # Estimar classes
  aux = 0
  for j in vet_sup[:,0]:
    if j < K.shape[0]:
      aux = aux + (y_reset_index_teste.iloc[j].values[0] * alpha[j] * K.iloc[j,:])
  y_est_teste = np.sign((aux + b).T)
  y_est_teste = pd.DataFrame(y_est_teste)

  # Vetores de índices reais para comparação
  indices_teste = y_reset_index_teste.T.values[0]
  indices_teste = indices_teste.astype(float)

  # Vetores de índices previstos para comparação
  indices_previstos_teste = y_est_teste.T.values[0]
  indices_previstos_teste = indices_previstos_teste.astype(float)
  print(f'Matriz de confusão:\n{confusion_matrix(indices_teste, indices_previstos_teste)}')

  # Teste de acurácia com labels corretos e labels previstos (classificados)
  accuracy_teste = getAccuracy(indices_teste, indices_previstos_teste, len(indices_teste))
  all_accuracy_teste.append(accuracy_teste)
  print(f'Acurácia de teste dessa interação: {int(accuracy_teste)}%')
  print('#####################################################################')
  if p < 14:
    print('|/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/_')

  # Melhor acurácia e hiperparâmetros
  if accuracy_teste > melhor_acuracia:
    melhor_acuracia = accuracy_teste
    melhor_C = C
    melhor_gama = gama

print('\n')
# Média total das acurácias de teste
print(f'Média das acurácias de teste: {int(np.mean(all_accuracy_teste))}%')
# Melhor hiperparâmetro
print(f'No melhor valor de acurácia do teste, que foi igual a {int(melhor_acuracia)}%, o melhor valor para hiperparâmetro C foi {melhor_C} e o melhor para hiperparâmetro gama foi {melhor_gama}')

#####################################################################
Interação: 1/15
Valor de d = 27
Matriz de confusão:
[[141   0]
 [  0   9]]
Acurácia de teste dessa interação: 100%
#####################################################################
|/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/_
#####################################################################
Interação: 2/15
Valor de d = 49
Matriz de confusão:
[[141   0]
 [  0   9]]
Acurácia de teste dessa interação: 100%
#####################################################################
|/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/_
#####################################################################
Interação: 3/15
Valor de d = 44
Matriz de confusão:
[[141   0]
 [  4   5]]
Acurácia de teste dessa interação: 97%
#####################################################################
|/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/__\||/_
##########################

Nota: O kernel RBF consegue uma ótima classificação. Tendo média geral de acurácia do teste de 99% e ótimos valores para recall e precisão também, já que as classes conseguem ser bem separadas sem nenhum erro de classificação em quase todos os casos.